name: Deploy Infrastructure

on:
  push:
    branches: [master]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    needs:
      - lint
    permissions:
      pull-requests: write

    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - run: terraform init
