name: Deploy Infrastructure

on:
  push:
    branches:
      - master

jobs:
  colmena-apply:
    name: Colmena Apply
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@v30

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.7.0
        with:
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          known_hosts: ${{ secrets.MINESHSPC_KNOWN_HOSTS }}

      - name: Unlock secrets
        env:
          GIT_CRYPT_SECRET: ${{ secrets.GIT_CRYPT_SECRET }}
        run: |
          echo "$GIT_CRYPT_SECRET" | base64 -d > "/tmp/git-crypt-secret"
          nix develop --command git crypt unlock /tmp/git-crypt-secret
          rm /tmp/git-crypt-secret

      - name: colmena apply
        run: |
          nix develop --command git status
          nix develop --command colmena apply
