name: Deploy Infrastructure

on:
  push:
    branches:
      - master

jobs:
  colmena-apply:
    name: Colmena Apply
    runs-on: ubuntu-latest
    environment: production
    env:
      GIT_CRYPT_SECRET: ${{ secrets.GIT_CRYPT_SECRET }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: nevarro-space/infrastructure-secrets
          token: ${{ secrets.SECRET_REPO_CLONE_TOKEN }}
          path: infrastructure-secrets

      - uses: nixbuild/nix-quick-install-action@v30

      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_SECRET }}
          RUN_DIR: infrastructure-secrets

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.7.0
        with:
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          known_hosts: ${{ secrets.MINESHSPC_KNOWN_HOSTS }}

      - name: colmena apply
        uses: workflow/nix-shell-action@v3.4.0
        with:
          flakes-from-devshell: true
          script: |
            cd infrastructure
            colmena apply
